/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type Credential = {
  _id: string;
  _type: "credential";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  type?: "education" | "certification";
  title?: string;
  institution?: string;
  year?: string;
  date?: string;
  description?: string;
  details?: Array<string>;
  duration?: string;
  location?: string;
  certificateUrl?: string;
  skills?: Array<string>;
  status?: "Completado" | "En progreso";
  order?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  longDescription?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  technologies?: Array<string>;
  frameworks?: Array<string>;
  languages?: Array<string>;
  roles?: Array<string>;
  links?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
  status?: "Completado" | "En desarrollo";
  year?: string;
  featured?: boolean;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  company?: string;
  period?: string;
  location?: string;
  summary?: string;
  responsibilities?: Array<string>;
  achievements?: Array<string>;
  technologies?: Array<string>;
  projectType?: string;
  order?: number;
};

export type SkillCategory = {
  _id: string;
  _type: "skillCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  order?: number;
  skills?: Array<{
    name?: string;
    highlights?: Array<string>;
    _key: string;
  }>;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  eyebrow?: string;
  summary?: string;
  bio?: string;
  location?: string;
  availability?: string;
  email?: string;
  phone?: string;
  cv?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  socialLinks?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
  aboutSections?: Array<{
    id?: Slug;
    title?: string;
    body?: Array<string>;
    _key: string;
  }>;
  seo?: {
    title?: string;
    description?: string;
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type ExternalLink = {
  _type: "externalLink";
  label?: string;
  url?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Credential
  | SanityImageAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Experience
  | SkillCategory
  | SanityFileAssetReference
  | SiteSettings
  | Slug
  | ExternalLink
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: PORTFOLIO_QUERY
// Query: {  "settings": *[_type == "siteSettings" && _id == "siteSettings"][0]{    name,    role,    eyebrow,    summary,    bio,    location,    availability,    email,    phone,    "cvUrl": cv.asset->url,    "avatar": select(defined(avatar.asset) => {      "url": avatar.asset->url,      "alt": avatar.alt    }),    socialLinks[]{label, url},    aboutSections[]{      "id": id.current,      title,      body    },    seo{title, description}  },  "skills": *[_type == "skillCategory"] | order(order asc){    "id": _id,    title,    description,    order,    skills[]{name, highlights}  },  "experience": *[_type == "experience"] | order(order asc){    "id": _id,    title,    company,    period,    location,    summary,    responsibilities,    achievements,    technologies,    projectType,    order  },  "projects": *[_type == "project"] | order(order asc){    "id": _id,    name,    description,    longDescription,    technologies,    frameworks,    languages,    roles,    links[]{label, url},    status,    year,    featured,    order,    "image": select(defined(image.asset) => {      "url": image.asset->url,      "alt": image.alt    })  },  "credentials": *[_type == "credential"] | order(order asc){    "id": _id,    type,    title,    institution,    year,    date,    description,    details,    duration,    location,    certificateUrl,    skills,    status,    order  }}
export type PORTFOLIO_QUERY_RESULT = {
  settings: {
    name: string | null;
    role: string | null;
    eyebrow: string | null;
    summary: string | null;
    bio: string | null;
    location: string | null;
    availability: string | null;
    email: string | null;
    phone: string | null;
    cvUrl: string | null;
    avatar: {
      url: string | null;
      alt: string | null;
    };
    socialLinks: Array<{
      label: string | null;
      url: string | null;
    }> | null;
    aboutSections: Array<{
      id: string | null;
      title: string | null;
      body: Array<string> | null;
    }> | null;
    seo: {
      title: string | null;
      description: string | null;
    } | null;
  } | null;
  skills: Array<{
    id: string;
    title: string | null;
    description: string | null;
    order: number | null;
    skills: Array<{
      name: string | null;
      highlights: Array<string> | null;
    }> | null;
  }>;
  experience: Array<{
    id: string;
    title: string | null;
    company: string | null;
    period: string | null;
    location: string | null;
    summary: string | null;
    responsibilities: Array<string> | null;
    achievements: Array<string> | null;
    technologies: Array<string> | null;
    projectType: string | null;
    order: number | null;
  }>;
  projects: Array<{
    id: string;
    name: string | null;
    description: string | null;
    longDescription: string | null;
    technologies: Array<string> | null;
    frameworks: Array<string> | null;
    languages: Array<string> | null;
    roles: Array<string> | null;
    links: Array<{
      label: string | null;
      url: string | null;
    }> | null;
    status: "Completado" | "En desarrollo" | null;
    year: string | null;
    featured: boolean | null;
    order: number | null;
    image: {
      url: string | null;
      alt: string | null;
    };
  }>;
  credentials: Array<{
    id: string;
    type: "certification" | "education" | null;
    title: string | null;
    institution: string | null;
    year: string | null;
    date: string | null;
    description: string | null;
    details: Array<string> | null;
    duration: string | null;
    location: string | null;
    certificateUrl: string | null;
    skills: Array<string> | null;
    status: "Completado" | "En progreso" | null;
    order: number | null;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '{\n  "settings": *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    name,\n    role,\n    eyebrow,\n    summary,\n    bio,\n    location,\n    availability,\n    email,\n    phone,\n    "cvUrl": cv.asset->url,\n    "avatar": select(defined(avatar.asset) => {\n      "url": avatar.asset->url,\n      "alt": avatar.alt\n    }),\n    socialLinks[]{label, url},\n    aboutSections[]{\n      "id": id.current,\n      title,\n      body\n    },\n    seo{title, description}\n  },\n  "skills": *[_type == "skillCategory"] | order(order asc){\n    "id": _id,\n    title,\n    description,\n    order,\n    skills[]{name, highlights}\n  },\n  "experience": *[_type == "experience"] | order(order asc){\n    "id": _id,\n    title,\n    company,\n    period,\n    location,\n    summary,\n    responsibilities,\n    achievements,\n    technologies,\n    projectType,\n    order\n  },\n  "projects": *[_type == "project"] | order(order asc){\n    "id": _id,\n    name,\n    description,\n    longDescription,\n    technologies,\n    frameworks,\n    languages,\n    roles,\n    links[]{label, url},\n    status,\n    year,\n    featured,\n    order,\n    "image": select(defined(image.asset) => {\n      "url": image.asset->url,\n      "alt": image.alt\n    })\n  },\n  "credentials": *[_type == "credential"] | order(order asc){\n    "id": _id,\n    type,\n    title,\n    institution,\n    year,\n    date,\n    description,\n    details,\n    duration,\n    location,\n    certificateUrl,\n    skills,\n    status,\n    order\n  }\n}': PORTFOLIO_QUERY_RESULT;
  }
}
