import type { PortfolioContent } from "./types";

export const fallbackContent: PortfolioContent = {
  settings: {
    name: "Felipe Henríquez",
    role: "Desarrollador Full Stack",
    eyebrow: "Ingeniero en Informática · Santiago, Chile",
    summary:
      "Construyo productos web claros, mantenibles y orientados a resolver problemas reales con React, Node.js y Spring Boot.",
    bio:
      "Ingeniero en Informática y desarrollador full stack. Trabajo de extremo a extremo: desde interfaces accesibles hasta APIs, datos y despliegue cloud, con foco en código simple y equipos que mejoran continuamente.",
    location: "Santiago, Chile",
    availability: "Disponible para oportunidades full stack",
    email: "felipe.daniel.henriquez@gmail.com",
    phone: "+56 9 8469 2943",
    socialLinks: [],
    aboutSections: [
      {
        id: "mi-historia",
        title: "Mi historia",
        body: [
          "Soy Felipe Henríquez, desarrollador full stack con formación en Ingeniería en Informática y una especialización intensiva en Generation Chile. Mi interés por la tecnología nació de querer entender y mejorar las aplicaciones que usamos a diario.",
          "He trabajado tanto en frontend como en backend, conectando interfaces intuitivas con arquitecturas de servidor confiables. Cada proyecto es una oportunidad para aprender, medir y simplificar.",
        ],
      },
      {
        id: "mis-objetivos",
        title: "Mis objetivos",
        body: [
          "Quiero aportar en equipos que valoren las buenas prácticas, la innovación útil y el crecimiento continuo. Busco crear soluciones escalables y mantenibles sin perder de vista a las personas que las usan.",
          "Me interesa profundizar en arquitectura, cloud y liderazgo técnico, compartiendo conocimiento y ayudando a que el equipo tome mejores decisiones.",
        ],
      },
      {
        id: "mis-pasiones",
        title: "Lo que me mueve",
        body: [
          "Disfruto explorar herramientas que mejoran el ciclo de desarrollo, colaborar con otras personas y convertir necesidades ambiguas en soluciones concretas.",
          "Creo en el aprendizaje compartido, la documentación que sirve y la retroalimentación temprana.",
        ],
      },
      {
        id: "mi-filosofia",
        title: "Mi filosofía de desarrollo",
        body: [
          "Cada línea de código debe tener un propósito. Prefiero soluciones pequeñas, probadas y comprensibles antes que abstracciones difíciles de sostener.",
          "Calidad significa accesibilidad, rendimiento, seguridad y una base que el siguiente desarrollador pueda entender sin adivinar.",
        ],
      },
    ],
    seo: {
      title: "Felipe Henríquez · Desarrollador Full Stack",
      description:
        "Portafolio de Felipe Henríquez, ingeniero en informática y desarrollador full stack especializado en React, Node.js y Spring Boot.",
    },
  },
  skills: [
    {
      id: "languages",
      title: "Lenguajes",
      description: "Bases que utilizo para construir productos web y servicios.",
      order: 1,
      skills: [
        { name: "JavaScript", highlights: ["ES2023", "Async/Await", "Event Loop", "Testing"] },
        { name: "TypeScript", highlights: ["Tipos estrictos", "Genéricos", "Type guards", "Contratos"] },
        { name: "Java", highlights: ["POO", "APIs REST", "Spring", "JUnit"] },
        { name: "SQL", highlights: ["Modelado", "Joins", "Transacciones", "Índices"] },
      ],
    },
    {
      id: "frontend",
      title: "Frontend",
      description: "Interfaces rápidas, accesibles y fáciles de mantener.",
      order: 2,
      skills: [
        { name: "React", highlights: ["Componentes", "Hooks", "Rendimiento", "Testing"] },
        { name: "Next.js", highlights: ["App Router", "Server Components", "SEO", "Caching"] },
        { name: "CSS y Tailwind", highlights: ["Responsive", "Design tokens", "Accesibilidad", "Animación"] },
      ],
    },
    {
      id: "backend",
      title: "Backend",
      description: "Servicios seguros con límites e interfaces explícitas.",
      order: 3,
      skills: [
        { name: "Node.js", highlights: ["REST", "Validación", "Autenticación", "Integraciones"] },
        { name: "Spring Boot", highlights: ["JPA", "Security", "Testing", "Configuración"] },
        { name: "Datos", highlights: ["MySQL", "PostgreSQL", "MongoDB", "Diseño de esquemas"] },
      ],
    },
    {
      id: "delivery",
      title: "Entrega y operación",
      description: "Herramientas para llevar una solución desde el código hasta producción.",
      order: 4,
      skills: [
        { name: "Cloud", highlights: ["AWS", "GCP", "Vercel", "CloudWatch"] },
        { name: "DevOps", highlights: ["Git", "Docker", "CI/CD", "Observabilidad"] },
        { name: "Trabajo en equipo", highlights: ["Scrum", "Documentación", "Soporte", "Mentoría"] },
      ],
    },
  ],
  experience: [
    {
      id: "freelance-woocommerce",
      title: "Desarrollador Freelance",
      company: "Proyectos WooCommerce",
      period: "2025",
      location: "Santiago, Chile · Remoto",
      summary:
        "Implementación de tiendas online para microemprendedoras, desde la configuración inicial hasta la capacitación y el soporte.",
      responsibilities: [
        "Implementación y personalización de tiendas WooCommerce",
        "Integración de pagos, inventario y flujos operativos",
        "Optimización de experiencia responsive y rendimiento",
        "Capacitación y soporte técnico a clientes",
      ],
      achievements: [
        "Entrega de soluciones ajustadas al flujo real de cada negocio",
        "Mejoras medibles en tiempos de carga y autonomía del cliente",
      ],
      technologies: ["WordPress", "WooCommerce", "PHP", "MySQL", "JavaScript", "CSS"],
      projectType: "E-commerce",
      order: 1,
    },
    {
      id: "etpay",
      title: "Customer Specialist IT",
      company: "ETPAY SpA",
      period: "Jun 2021 — Dic 2021",
      location: "Santiago, Chile",
      summary:
        "Soporte técnico para una plataforma de pagos, conectando las necesidades de clientes con el equipo de desarrollo.",
      responsibilities: [
        "Monitoreo y análisis de incidencias con AWS CloudWatch",
        "Soporte a integraciones mediante APIs REST",
        "Diagnóstico a partir de logs y consultas SQL",
        "Documentación y escalamiento con desarrollo",
      ],
      achievements: [
        "Mejora de tiempos de diagnóstico mediante documentación reutilizable",
        "Seguimiento proactivo de incidentes críticos para clientes",
      ],
      technologies: ["AWS CloudWatch", "REST APIs", "SQL", "Postman", "Jira"],
      projectType: "Fintech",
      order: 2,
    },
    {
      id: "ducklife",
      title: "Desarrollador Shopify · Práctica",
      company: "Ducklife Media",
      period: "Oct 2020 — Dic 2020",
      location: "Santiago, Chile",
      summary:
        "Personalización de tiendas Shopify con foco en experiencia responsive, consistencia visual y calidad de implementación.",
      responsibilities: [
        "Modificación de temas y componentes con Liquid",
        "Implementación responsive a partir de diseños",
        "Pruebas cross-browser y corrección de defectos",
      ],
      achievements: ["Entrega de mejoras visuales en múltiples tiendas de clientes"],
      technologies: ["Shopify", "Liquid", "HTML", "CSS", "JavaScript", "Git"],
      projectType: "E-commerce",
      order: 3,
    },
  ],
  projects: [
    {
      id: "ecomarket",
      name: "Ecomarket",
      description: "E-commerce full stack de productos sostenibles.",
      longDescription:
        "Plataforma con catálogo, inventario, carrito, autenticación y administración, construida para practicar un flujo completo entre frontend, API y datos.",
      technologies: ["React", "Spring Boot", "MySQL", "JWT", "Vercel", "GCP"],
      frameworks: ["React", "Spring Boot"],
      languages: ["JavaScript", "Java", "SQL"],
      roles: ["Frontend", "Backend", "Full Stack"],
      links: [],
      status: "Completado",
      year: "2024",
      featured: true,
      order: 1,
    },
    {
      id: "banco-simple",
      name: "BancoSimple",
      description: "Aplicación bancaria simulada con autenticación JWT.",
      longDescription:
        "Producto educativo con gestión de cuentas, transferencias e historial de movimientos, orientado a practicar seguridad y consistencia de datos.",
      technologies: ["React", "Spring Boot", "MySQL", "JWT", "Spring Security"],
      frameworks: ["React", "Spring Boot"],
      languages: ["JavaScript", "Java", "SQL"],
      roles: ["Frontend", "Backend", "Full Stack"],
      links: [],
      status: "Completado",
      year: "2024",
      featured: true,
      order: 2,
    },
    {
      id: "task-cli",
      name: "Gestor de Tareas CLI",
      description: "Herramienta interactiva para organizar tareas desde la terminal.",
      longDescription:
        "Aplicación Node.js para crear, priorizar y completar tareas mediante un flujo de línea de comandos sencillo.",
      technologies: ["Node.js", "Inquirer", "JSON"],
      frameworks: ["Node.js"],
      languages: ["JavaScript"],
      roles: ["Backend", "CLI"],
      links: [],
      status: "Completado",
      year: "2024",
      featured: true,
      order: 3,
    },
    {
      id: "restaurant-manager",
      name: "API RestaurantManager",
      description: "API REST para la operación de un restaurante.",
      longDescription:
        "Backend para menús, pedidos, inventario y reportes, con documentación y pruebas automatizadas.",
      technologies: ["Spring Boot", "PostgreSQL", "Swagger", "JUnit", "Docker"],
      frameworks: ["Spring Boot"],
      languages: ["Java", "SQL"],
      roles: ["Backend", "API"],
      links: [],
      status: "Completado",
      year: "2023",
      featured: false,
      order: 4,
    },
  ],
  credentials: [
    {
      id: "generation",
      type: "education",
      title: "Bootcamp Full Stack · 540 h",
      institution: "Generation Chile",
      year: "2025",
      date: "2025-01-15",
      description: "Programa intensivo de desarrollo full stack y habilidades profesionales.",
      details: ["React y Node.js", "Spring Boot", "SQL y NoSQL", "Testing, CI/CD y cloud"],
      duration: "540 horas",
      location: "Santiago, Chile",
      skills: ["React", "Node.js", "Spring Boot"],
      status: "Completado",
      order: 1,
    },
    {
      id: "duoc",
      type: "education",
      title: "Ingeniería en Informática",
      institution: "Duoc UC",
      year: "2021",
      date: "2021-12-15",
      description: "Título profesional con énfasis en desarrollo de software y sistemas de información.",
      details: [],
      duration: "4 años",
      location: "Santiago, Chile",
      skills: ["Java", "SQL", "Diseño de software"],
      status: "Completado",
      order: 2,
    },
    {
      id: "react-udemy",
      type: "certification",
      title: "React: de cero a experto",
      institution: "Udemy",
      year: "2024",
      date: "2024-11-20",
      description: "Curso de React desde fundamentos hasta patrones y testing.",
      details: [],
      duration: "40 horas",
      skills: ["React", "Redux", "Testing"],
      status: "Completado",
      order: 3,
    },
    {
      id: "docker-udemy",
      type: "certification",
      title: "Docker: guía práctica para desarrolladores",
      institution: "Udemy",
      year: "2024",
      date: "2024-10-15",
      description: "Containerización y prácticas para entornos de desarrollo y producción.",
      details: [],
      duration: "25 horas",
      skills: ["Docker", "DevOps"],
      status: "Completado",
      order: 4,
    },
  ],
};
